### ISSUE TITLE
ReferenceInput doesn't render suggestions for Autocomplete properly

### ISSUE THREAD

**Issue by cyberlake** [benwinding/react-admin-firebase#119] opened 2020-05-10 20:54 UTC
Trying to reference another resource with `ReferenceInput`. The initial state works perfectly, it loads suggestions. However, when typing any character for searching, it doesn't retrieve any suggestions. 
```
<ReferenceInput reference="tags" source="tag_ids" label="Tags">
        <AutocompleteInput optionText="name" />
</ReferenceArrayInput>
```

From logs seems like  `collectionQuery` is `undefined`. Log line:

```
🔥r-a-f:  resourceManager.TryGetResourcePromise {relativePath: "categories", collectionQuery: undefined}
🔥r-a-f:  resourceManager.initPath() {absolutePath: "categories", hasBeenInited: true}
```

**Comment by benwinding** [comment] 2020-05-26 06:31
Hey @cyberlake,

Apologies for the late response. Are you still experiencing this issue? 

Sorry, I'm unable to reproduce it here, are you able to give me some more information on how the problem occurs?

**Comment by cyberlake** [comment] 2020-05-27 17:08
Hi @benwinding. Thanks for the reply.

Yes, still having the same issue. I created [codesanbox](https://codesandbox.io/s/react-admin-firebase-20cx5?file=/src/App.js), you can reproduce same issue there. (I couldn't share my firebase details). 

- Edit firebase config in `App.js`
- Create multiple tags with different names
- Create a blog post and in the `tags` input try to type the name of any created tag. The dropdown should render suggestions.

My guess is that the returned list to `AutocompleteInput` is empty.

**Comment by benwinding** [comment] 2020-05-27 23:56
> Yes, still having the same issue. I created codesanbox, you can reproduce same issue there. (I couldn't share my firebase details).

Thanks @cyberlake, that makes it way easier to diagnose. 

Okay I can think I can see the problem now. The items seem to show as expected, then disappear as typing continues... hmmm, will look into it furthur

![Peek 2020-05-28 09-16](https://user-images.githubusercontent.com/11782590/83083066-4501c700-a0c4-11ea-936b-58466cee88ae.gif)

**Comment by cyberlake** [comment] 2020-05-28 09:38
Here's the same app with one of the react-admin `dataproviders`: [codesandbox](https://codesandbox.io/s/react-admin-bug-referencearrayinput-d62in?file=/src/App.js). Suggestions are working here.

`The items seem to show as expected, then disappear as typing continues...` might be that react-admin does the search within list first, and then gets results from firebase, which are empty. 

Thanks for looking into this.

**Comment by benwinding** [comment] 2020-05-28 14:16
Thanks for checking back in. Looks like I've found a fix to the bug! 

``` jsx
<ReferenceInput reference="tags" source="tag_ids" label="Tags"
   // Adding this fixes the issue
   filterToQuery={searchText => ({ name: searchText })} 
>
        <AutocompleteInput optionText="name" />
</ReferenceArrayInput>
```

There's an error in the handling of the _default filter_ of `{ q: [searchText] }`, which I was unaware of and doesn't seem to be in the new documentation? (I only found a reference [in the archived admin-on-rest repository](https://github.com/marmelab/admin-on-rest/blob/master/docs/Inputs.md#referenceinput)).

> ReferenceInput passes a setFilter function as prop to its child component. It uses the value to create a filter for the query - by default `{ q: [searchText] }`. You can customize the mapping searchText => searchQuery by setting a custom filterToQuery function prop:

Anyway, this issue will be fixed in the next version and this issue will be closed. But for now just try using the explicit `filterToQuery` function as shown above.

Thanks for reporting it and helping fix it!

Cheers,
Ben

**Comment by cyberlake** [comment] 2020-05-28 18:52
Perfect, workaround works. 👍 

Feel free to close the Issue. 

Thanks for the quick response and workaround, much appreciated!

**Closed** 2020-11-20 17:49 UTC
